from enum import Enum
import math

ESTABLISH_CONNECTION_CODE = -1
CONNECTION_ESTABLISHMENT_INTERVAL = 0.5
CONNECTION_TIMEOUT = 1
WINDOW_SIZE = 5
TIMEOUT_GO_BACK_N_SENDER = 0.2  # sec
TIMEOUT_SEL_REPEAT_SENDER = 0.2
# MAX_LAST_PACKET_SENDING = 1
# TIMEOUT_LAST_PACKET_SENDER = 0.5
TIMEOUT_RECEIVER = 0.2
ERROR_PROBABILITY = 0.1

TRANSMISSION_TIMEOUT = 5


class TransmissionProtocol(Enum):
    ALGORITHM_TYPE_GBN = 1
    ALGORITHM_TYPE_SR = 2


# TRANSMISSION_PROTOCOL_TYPE = TransmissionProtocol.ALGORITHM_TYPE_GBN
TRANSMISSION_PROTOCOL_TYPE = TransmissionProtocol.ALGORITHM_TYPE_SR

# Network parameters
MIRROR_TIMEOUT = 810
FOCUS_TIMEOUT = 800
LIGHT_SRC_TIMEOUT = 800
LIGHT_SRC_MOVING_TIME_INTERVAL = 780
MIRROR_TO_LIGHT_SRC_TIMEOUT = 20
MIRROR_TO_FOCUS_TIMEOUT = 20
MIRROR_TO_MIRROR_TIMEOUT = 20

ROTATION_DELTA_RAD = -math.pi / 180
FOCUS_HITTING_PRECISION = 0.1

MSG_HELLO = "hello"
MSG_TAKE_ADJUSTING_CONTROL = "take_adjusting_control"

HELLO_TIMEOUT = 5

NODES_NUMBER = 5
FOCUS_COORDINATE = [0, 4]
LIGHT_SOURCE_COORDINATE = [-1, 7]

NETWORK_TIMEOUT = 850


